apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: anomaly-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: anomaly_detection
        volumeMounts:
        - name: timescaledb-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: timescaledb-data
        persistentVolumeClaim:
          claimName: timescaledb-data
      - name: init-script
        configMap:
          name: timescaledb-init-script
