apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka1-data
  namespace: anomaly-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka2-data
  namespace: anomaly-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
